name: nightly build at 1pm

on:
  push: 
  schedule:
   - cron: '0 1 * * *'
jobs:
   nightly_build:
   runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run unit test
        run: mvn test 
        
      - name: Build with Maven   
        run: mvn -DskipTests -8 package --no-transfer-progress --file ./pom.xl

      - uses: actions/upload-artifact@master
        with:
            name: digibank.war
            path: ./target/*digitalbank*.war
